In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

### Making a checkpoint and defining inputs

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours',
                                            'Day of the Week', 'Daily Work Load Average(in Minutes) ', 'Distance to Work'],axis=1)

In [11]:
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0        0        0        0        1            7                     289   
1        0        0        0        0            7                     118   
2        0        0        0        1            7                     179   
3        1        0        0        0            7                     279   
4        0        0        0        1            7                     289   

   Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0   33               30          0         2     1                      1  
1   50               31          0         1     0                      0  
2   38               31          0         0     0                      0  
3   39               24          0         2     0                      1  
4   33               30          0         2     1                      0

In [12]:
data_with_targets.shape[1]

12

In [13]:
data_with_targets.iloc[:,:(data_with_targets.shape[1]-1)]

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0          0        0        0        1            7                     289   
1          0        0        0        0            7                     118   
2          0        0        0        1            7                     179   
3          1        0        0        0            7                     279   
4          0        0        0        1            7                     289   
..       ...      ...      ...      ...          ...                     ...   
695        1        0        0        0            5                     179   
696        1        0        0        0            5                     225   
697        1        0        0        0            5                     330   
698        0        0        0        1            5                     235   
699        0        0        0        1            5                     291   

     Age  Body Mass Index  Education  Children  Pets  
0     33               30          0         2     1  
1     50               31          0         1     0  
2     38               31          0         0     0  
3     39               24          0         2     0  
4     33               30          0         2     1  
..   ...              ...        ...       ...   ...  
695   40               22          1         2     0  
696   28               24          0         1     2  
697   28               25          1         0     0  
698   32               25          1         0     0  
699   40               25          0         1     1  

[700 rows x 11 columns]

In [14]:
data_with_targets.iloc[:,:-1]

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0          0        0        0        1            7                     289   
1          0        0        0        0            7                     118   
2          0        0        0        1            7                     179   
3          1        0        0        0            7                     279   
4          0        0        0        1            7                     289   
..       ...      ...      ...      ...          ...                     ...   
695        1        0        0        0            5                     179   
696        1        0        0        0            5                     225   
697        1        0        0        0            5                     330   
698        0        0        0        1            5                     235   
699        0        0        0        1            5                     291   

     Age  Body Mass Index  Education  Children  Pets  
0     33               30          0         2     1  
1     50               31          0         1     0  
2     38               31          0         0     0  
3     39               24          0         2     0  
4     33               30          0         2     1  
..   ...              ...        ...       ...   ...  
695   40               22          1         2     0  
696   28               24          0         1     2  
697   28               25          1         0     0  
698   32               25          1         0     0  
699   40               25          0         1     1  

[700 rows x 11 columns]

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [16]:
unscaled_inputs

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0          0        0        0        1            7                     289   
1          0        0        0        0            7                     118   
2          0        0        0        1            7                     179   
3          1        0        0        0            7                     279   
4          0        0        0        1            7                     289   
..       ...      ...      ...      ...          ...                     ...   
695        1        0        0        0            5                     179   
696        1        0        0        0            5                     225   
697        1        0        0        0            5                     330   
698        0        0        0        1            5                     235   
699        0        0        0        1            5                     291   

     Age  Body Mass Index  Education  Children  Pets  
0     33               30          0         2     1  
1     50               31          0         1     0  
2     38               31          0         0     0  
3     39               24          0         2     0  
4     33               30          0         2     1  
..   ...              ...        ...       ...   ...  
695   40               22          1         2     0  
696   28               24          0         1     2  
697   28               25          1         0     0  
698   32               25          1         0     0  
699   40               25          0         1     1  

[700 rows x 11 columns]

### Standardization 

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin

In [19]:
class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self,X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [20]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [21]:
#olumns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work','Age',
                #   'Daily Work Load Average(in Minutes) ', 'Body Mass Index','Children', 'Pets']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [22]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [23]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [24]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month Value',
                      'Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets'])

In [25]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [26]:
scaled_inputs 

Reason1   Reason2   Reason3   Reason4  Month Value  \
0   -0.577350 -0.092981 -0.396264  0.901927     0.182726   
1   -0.577350 -0.092981 -0.396264 -1.108738     0.182726   
2   -0.577350 -0.092981 -0.396264  0.901927     0.182726   
3    1.732051 -0.092981 -0.396264 -1.108738     0.182726   
4   -0.577350 -0.092981 -0.396264  0.901927     0.182726   
..        ...       ...       ...       ...          ...   
695  1.732051 -0.092981 -0.396264 -1.108738    -0.388293   
696  1.732051 -0.092981 -0.396264 -1.108738    -0.388293   
697  1.732051 -0.092981 -0.396264 -1.108738    -0.388293   
698 -0.577350 -0.092981 -0.396264  0.901927    -0.388293   
699 -0.577350 -0.092981 -0.396264  0.901927    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [27]:
scaled_inputs.shape

(700, 11)

### Split the Dataset into train and test

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
train_test_split(scaled_inputs, targets)

[      Reason1   Reason2   Reason3   Reason4  Month Value  \
 90  -0.577350 -0.092981 -0.396264  0.901927     1.324766   
 281 -0.577350 -0.092981 -0.396264  0.901927     0.753746   
 6   -0.577350 -0.092981  2.523573 -1.108738     0.182726   
 251 -0.577350 -0.092981 -0.396264 -1.108738     0.182726   
 198 -0.577350 -0.092981  2.523573 -1.108738    -0.673803   
 ..        ...       ...       ...       ...          ...   
 155 -0.577350 -0.092981 -0.396264  0.901927    -0.959313   
 309 -0.577350 -0.092981 -0.396264  0.901927     1.039256   
 565  1.732051 -0.092981 -0.396264 -1.108738     1.610276   
 645 -0.577350 -0.092981 -0.396264  0.901927    -0.959313   
 564 -0.577350 -0.092981  2.523573 -1.108738     1.610276   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 90                 0.040034 -1.320435        -0.643782          0 -0.019280   
 281                1.036026  0.562059        -0.408580          0 -0.019280   
 6                  2.0923

In [30]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, test_size = 0.2, random_state = 20)



In [31]:
x_train.shape, y_train.shape

((560, 11), (560,))

In [32]:
x_test.shape, y_test.shape

((140, 11), (140,))

### Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
reg = LogisticRegression()

In [35]:
reg.fit(x_train, y_train)

LogisticRegression()

In [36]:
reg.score(x_train, y_train)

0.8071428571428572

### Manually check the accuracy

In [37]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [38]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [39]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [40]:
np.sum((model_outputs == y_train))

452

In [41]:
model_outputs.shape[0]

560

In [42]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.8071428571428572

### Creating a summary table

In [43]:
reg.intercept_

array([-0.10565725])

In [44]:
reg.coef_

array([[ 2.00932757,  0.32986271,  1.92738048,  1.16501846,  0.25214803,
         0.6248957 , -0.19147367,  0.30301662, -0.4961633 ,  0.32837295,
        -0.49723675]])

In [45]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [46]:
feature_name = unscaled_inputs.columns.values

In [47]:
summary_table = pd.DataFrame (columns=['Feature Name'], data = feature_name)
summary_table

Feature Name
0                  Reason1
1                  Reason2
2                  Reason3
3                  Reason4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                    Pets

In [48]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [49]:
summary_table

Feature Name  Coefficient
0                  Reason1     2.009328
1                  Reason2     0.329863
2                  Reason3     1.927380
3                  Reason4     1.165018
4              Month Value     0.252148
5   Transportation Expense     0.624896
6                      Age    -0.191474
7          Body Mass Index     0.303017
8                Education    -0.496163
9                 Children     0.328373
10                    Pets    -0.497237

In [50]:
summary_table.index = summary_table.index + 1
summary_table

Feature Name  Coefficient
1                  Reason1     2.009328
2                  Reason2     0.329863
3                  Reason3     1.927380
4                  Reason4     1.165018
5              Month Value     0.252148
6   Transportation Expense     0.624896
7                      Age    -0.191474
8          Body Mass Index     0.303017
9                Education    -0.496163
10                Children     0.328373
11                    Pets    -0.497237

In [51]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature Name  Coefficient
1                  Reason1     2.009328
2                  Reason2     0.329863
3                  Reason3     1.927380
4                  Reason4     1.165018
5              Month Value     0.252148
6   Transportation Expense     0.624896
7                      Age    -0.191474
8          Body Mass Index     0.303017
9                Education    -0.496163
10                Children     0.328373
11                    Pets    -0.497237
0                Intercept    -0.105657

In [52]:
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -0.105657
1                  Reason1     2.009328
2                  Reason2     0.329863
3                  Reason3     1.927380
4                  Reason4     1.165018
5              Month Value     0.252148
6   Transportation Expense     0.624896
7                      Age    -0.191474
8          Body Mass Index     0.303017
9                Education    -0.496163
10                Children     0.328373
11                    Pets    -0.497237

## Interpreting the coefficients

In [53]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [54]:
summary_table

Feature Name  Coefficient  Odds_ratio
0                Intercept    -0.105657    0.899733
1                  Reason1     2.009328    7.458300
2                  Reason2     0.329863    1.390777
3                  Reason3     1.927380    6.871487
4                  Reason4     1.165018    3.205982
5              Month Value     0.252148    1.286787
6   Transportation Expense     0.624896    1.868051
7                      Age    -0.191474    0.825741
8          Body Mass Index     0.303017    1.353937
9                Education    -0.496163    0.608862
10                Children     0.328373    1.388707
11                    Pets    -0.497237    0.608209

In [55]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
1                  Reason1     2.009328    7.458300
3                  Reason3     1.927380    6.871487
4                  Reason4     1.165018    3.205982
6   Transportation Expense     0.624896    1.868051
2                  Reason2     0.329863    1.390777
10                Children     0.328373    1.388707
8          Body Mass Index     0.303017    1.353937
5              Month Value     0.252148    1.286787
0                Intercept    -0.105657    0.899733
7                      Age    -0.191474    0.825741
9                Education    -0.496163    0.608862
11                    Pets    -0.497237    0.608209

### Testing our model

In [57]:
reg.score(x_test, y_test)

0.7714285714285715

In [58]:
predicted_probability = reg.predict_proba(x_test)

predicted_probability

array([[0.69771425, 0.30228575],
       [0.63255613, 0.36744387],
       [0.41682746, 0.58317254],
       [0.80413838, 0.19586162],
       [0.06855804, 0.93144196],
       [0.29203536, 0.70796464],
       [0.32567268, 0.67432732],
       [0.07171699, 0.92828301],
       [0.86750253, 0.13249747],
       [0.75480394, 0.24519606],
       [0.06755132, 0.93244868],
       [0.01206229, 0.98793771],
       [0.0329145 , 0.9670855 ],
       [0.15963157, 0.84036843],
       [0.19767588, 0.80232412],
       [0.6317723 , 0.3682277 ],
       [0.73501203, 0.26498797],
       [0.08810758, 0.91189242],
       [0.43300295, 0.56699705],
       [0.02185658, 0.97814342],
       [0.76117772, 0.23882228],
       [0.80413838, 0.19586162],
       [0.33127329, 0.66872671],
       [0.33127329, 0.66872671],
       [0.16491649, 0.83508351],
       [0.82040606, 0.17959394],
       [0.52981572, 0.47018428],
       [0.89007674, 0.10992326],
       [0.07953087, 0.92046913],
       [0.80413838, 0.19586162],
       [0.

In [59]:
predicted_probability.shape

(140, 2)

In [60]:
predicted_probability[:,1]

array([0.30228575, 0.36744387, 0.58317254, 0.19586162, 0.93144196,
       0.70796464, 0.67432732, 0.92828301, 0.13249747, 0.24519606,
       0.93244868, 0.98793771, 0.9670855 , 0.84036843, 0.80232412,
       0.3682277 , 0.26498797, 0.91189242, 0.56699705, 0.97814342,
       0.23882228, 0.19586162, 0.66872671, 0.66872671, 0.83508351,
       0.17959394, 0.47018428, 0.10992326, 0.92046913, 0.19586162,
       0.92085447, 0.63710222, 0.7368191 , 0.94097236, 0.19586162,
       0.95611252, 0.14099333, 0.85642898, 0.32638828, 0.57717103,
       0.18477071, 0.40864515, 0.15934863, 0.1159566 , 0.83191774,
       0.75283659, 0.71963065, 0.30228575, 0.19141918, 0.17417181,
       0.60404051, 0.08483834, 0.70796464, 0.26720098, 0.8525426 ,
       0.40150052, 0.89961751, 0.19352866, 0.1042722 , 0.1111902 ,
       0.6929676 , 0.6928609 , 0.28428447, 0.87889914, 0.12674911,
       0.27280877, 0.0212598 , 0.14099333, 0.86346356, 0.87533047,
       0.14099333, 0.07590896, 0.9373612 , 0.40984351, 0.55675

## Save the model

In [ ]:
import pickle

In [62]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [63]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)